/**
 * App i18n dictionary (EN/ES). Store-free so the Zustand store can import the
 * Lang type + detector without a cycle. `es` is the source of truth; `en` must
 * match its shape (enforced by the `Dict` type).
 */

export type Lang = "es" | "en";

const es = {
  nav: {
    coach: "COACH",
    today: "HOY",
    calendar: "CALENDARIO",
    routine: "RUTINA",
    week: "SEMANA",
    equipment: "EQUIPO",
    progress: "PROGRESO",
    entreno: "ENTRENO",
    social: "AMIGOS",
    settings: "AJUSTES",
    themeLight: "TEMA CLARO",
    themeDark: "TEMA OSCURO",
  },
  // Capa social / liga (F4).
  social: {
    title: "AMIGOS",
    sub: "LIGA",
    leagueSoon: "Liga — próximamente",
    season: "TEMPORADA",
    noCloud: "Falta configurar la nube. Definí VITE_CLERK_PUBLISHABLE_KEY y VITE_CONVEX_URL para activar la liga.",
    signInHeading: "Entrá a la liga",
    signInSub: "Compará tu esfuerzo semanal con tus amigos. Solo stats derivadas — tus registros crudos nunca salen del dispositivo.",
    myGroups: "Mis grupos",
    noGroups: "Todavía no estás en ningún grupo. Creá uno o unite con un código.",
    createGroup: "Crear grupo",
    groupNamePlaceholder: "Nombre del grupo",
    create: "Crear",
    joinGroup: "Unirse por código",
    codePlaceholder: "Código de invitación",
    join: "Unirse",
    inviteCode: "Código",
    selectGroupHint: "Elegí un grupo para ver la tabla.",
    publish: "Publicar mis stats",
    publishing: "Publicando…",
    published: "Publicado",
    refresh: "Actualizar",
    autoPublish: "Se publica solo",
    leave: "Salir del grupo",
    emptyStandings: "Nadie publicó stats esta temporada todavía. Sé el primero.",
    colRank: "#",
    colAthlete: "ATLETA",
    colForma: "FORMA",
    colAdherence: "CUMPLE",
    colEffort: "ESFUERZO",
    colStreak: "RACHA",
    colLevel: "NIVEL",
    sortLabel: "ORDEN",
    sortWeek: "SEMANA",
    sortForma: "FORMA",
    you: "VOS",
    loading: "Cargando…",
    routines: "Rutinas del grupo",
    shareRoutine: "Compartir una rutina",
    chooseRoutine: "Elegí una rutina…",
    share: "Compartir",
    copy: "Copiar",
    copied: "Copiada ✓",
    unshare: "Quitar",
    noRoutines: "Nadie compartió rutinas todavía. Compartí una de las tuyas.",
    sharedBy: "por",
    mineTag: "TUYA",
    routineSets: "ej.",
    badRoutine: "No se pudo leer esa rutina.",
  },
  // Reto de grupo (F4) — un reto por grupo, objetivo + check-ins por atleta.
  challenge: {
    label: "Reto del grupo",
    none: "Este grupo no tiene un reto activo. Creá uno para todos.",
    createTitle: "Crear reto",
    titlePlaceholder: "Título del reto",
    targetDateLabel: "Fecha objetivo",
    create: "Crear reto",
    daysLeft: "días restantes",
    dayLeft: "día restante",
    lastDay: "último día",
    finished: "Finalizado",
    delete: "Eliminar reto",
    myGoal: "Mi objetivo",
    goalDescPlaceholder: "¿Qué querés lograr?",
    metricOptional: "Métrica (opcional)",
    metricLabelPlaceholder: "Etiqueta (p.ej. Peso)",
    metricUnitPlaceholder: "Unidad",
    metricStartPlaceholder: "Inicio",
    metricTargetPlaceholder: "Objetivo",
    saveGoal: "Guardar objetivo",
    saved: "Guardado",
    logProgress: "Registrar avance",
    currentValuePlaceholder: "Valor actual",
    pctPlaceholder: "% (0-100)",
    notePlaceholder: "Nota (opcional)",
    checkin: "Registrar",
    noEntries: "Nadie fijó su objetivo todavía. Fijá el tuyo.",
    noGoal: "Sin objetivo",
    progress: "Progreso",
    lastCheckin: "último avance",
  },
  muscle: { pull: "Tirón", push: "Empuje", core: "Core", legs: "Piernas" },
  context: { desk: "De escritorio", space: "Necesita espacio" },
  // Canonical "does the planned volume fit your work window" vocabulary — shared by Rutina,
  // Hoy and Coach so the wording + colors never drift.
  feasibility: {
    all: "TODO ENTRA",
    wontFit: "NO ENTRA",
    empty: "VACÍO",
    hint: "No entran en tu ventana de trabajo. Recortá volumen o ampliá el horario.",
  },
  // Canonical set-action vocabulary — the same three words in the toast, the panel and Hoy.
  // "later" reschedules (snooze by snoozeMinutes); "skip" drops it for today.
  actions: {
    done: "HECHO",
    later: "MÁS TARDE",
    skip: "SALTAR HOY",
    skipped: "SALTADO HOY",
  },
  today: {
    title: "HOY",
    weekdays: ["LUNES", "MARTES", "MIÉRCOLES", "JUEVES", "VIERNES", "SÁBADO", "DOMINGO"],
    rest: "DESCANSO",
    restTitle: "Día de descanso",
    restSub: "Hoy toca recuperar · mañana seguimos",
    restScreen: "DESCANSO · RECUPERACIÓN",
    restStatus: "SISTEMA EN REPOSO",
    restProtocol: "PROTOCOLO",
    restProtocolBody: "Sin series agendadas. El músculo crece en la pausa.",
    restTip1: "Hidratá y movete suave",
    restTip2: "Dormí tus horas",
    restNext: "PRÓXIMA SESIÓN",
    restNextValue: "MAÑANA",
    setsDone: "SERIES HECHAS",
    loadToday: "CARGA DE HOY",
    theDay: "EL DÍA",
    sets: "SERIES",
    now: "AHORA",
    in: "EN",
    min: "MIN",
    next: "PRÓXIMA",
    reps: "REPS",
    minutes: "MINUTOS",
    hours: "HORAS",
    stPending: "PENDIENTE",
    stDone: "HECHO",
    stSkipped: "SALTADO",
    stNow: "AHORA",
    stNext: "PRÓXIMA",
    outOfHours: "FUERA DE HORARIO · MAÑANA SE REPARTEN DE NUEVO",
    noRoutine: "SIN EJERCICIOS — ARMÁ TU RUTINA",
    logFree: "＋ REGISTRAR",
    logFreeTitle: "REGISTRAR SERIE LIBRE",
    logPick: "ELEGÍ EJERCICIO",
    logVariant: "VARIANTE",
    logCancel: "CANCELAR",
    logConfirm: "REGISTRAR",
    logged: "REGISTRADO",
    entrenoSession: "SESIÓN DE HOY",
    entrenoWindow: "VENTANA",
  },
  // Foco/DND: silence reminders for a window. Shared by panel + Ajustes.
  focus: {
    label: "FOCO",
    on: "EN FOCO",
    sub: "SIN AVISOS",
    remaining: "MIN RESTANTES",
    start: "Modo foco",
    hint: "Silencia los avisos por un rato. Las series siguen agendadas.",
    end: "TERMINAR FOCO",
    cancel: "CANCELAR",
  },
  panel: {
    noSets: "Sin series",
    next: "PRÓXIMA",
    now: "AHORA",
    min: "MIN",
    h: "H",
    reps: "REPS",
  },
  toast: {
    now: "AHORA",
    reps: "REPS",
  },
  update: {
    label: "ACTUALIZACIÓN",
    newVersion: "Nueva versión",
    downloading: "DESCARGANDO",
    ready: "LISTA PARA INSTALAR",
    failed: "FALLÓ LA DESCARGA — REINTENTÁ",
    install: "ACTUALIZAR Y REINICIAR",
    retry: "REINTENTAR",
    // — chequeo manual en Ajustes —
    section: "ACTUALIZACIONES",
    checkLabel: "Buscar actualizaciones",
    checkHint: "Consulta si hay una versión más nueva publicada.",
    checkBtn: "BUSCAR",
    currentVersion: "Versión actual",
    stChecking: "BUSCANDO…",
    stUpToDate: "ESTÁS AL DÍA",
    stAvailable: "HAY UNA NUEVA VERSIÓN",
    stError: "NO SE PUDO CONSULTAR",
  },
  settings: {
    title: "AJUSTES",
    sub: "CONFIGURACIÓN",
    appearance: "APARIENCIA",
    theme: "Tema",
    modeLight: "Claro",
    modeDark: "Oscuro",
    modeSystem: "Sistema",
    accent: "Acento",
    language: "IDIOMA",
    languageLabel: "Idioma de la app",
    panelSection: "PANEL FLOTANTE",
    showPanel: "Mostrar panel",
    showPanelHint: "Mini-ventana siempre visible con el próximo ejercicio.",
    notifications: "NOTIFICACIONES",
    notifLabel: "Avisos de microset",
    notifHint: "Te avisa cuando toca una serie.",
    snoozeLabel: "Tiempo de posponer",
    focusSection: "FOCO",
    work: "HORARIO LABORAL",
    start: "Inicio",
    end: "Fin",
    lunch: "ALMUERZO",
    from: "Desde",
    to: "Hasta",
    minRest: "DESCANSO MÍNIMO",
    between: "Entre series",
    coach: "COACH",
    provider: "Proveedor",
    model: "Modelo",
    modelHint: "Necesita ANTHROPIC_API_KEY en el entorno.",
    endpoint: "Endpoint",
    endpointHint: "OpenAI-compatible (Ollama / LM Studio).",
    goals: "OBJETIVOS",
    goalsPh: "Ej: mi primer muscle-up, 12 dominadas, bajar grasa…",
    diet: "DIETA",
    dietPh: "Ej: superávit leve, ~140 g de proteína…",
    constraints: "RESTRICCIONES",
    constraintsPh: "Ej: molestia en hombro derecho, sin saltos…",
    demo: "MODO DEMO",
    demoLabel: "Activar modo demo",
    demoHint: "Agenda series desde ahora, ignorando tu horario, para probar la app.",
    modules: "MÓDULOS",
    entrenoModuleLabel: "Entreno",
    entrenoModuleHint: "Sumá salidas (BJJ, gym, correr) a tu semana en Rutina, con reprogramación adaptativa si te la perdés.",
    socialModuleLabel: "Amigos",
    socialModuleHint: "Liga semanal opcional con amigos. Solo esfuerzo derivado; tus registros crudos nunca salen del dispositivo.",
    syncSection: "NUBE",
    syncLabel: "Sincronizar entre dispositivos",
    syncHint: "Espeja tu configuración (rutina, equipo, ejercicios, ajustes) vía la nube para tenerla igual en otro dispositivo. Opt-in; requiere iniciar sesión en Amigos. Tus registros no se sincronizan todavía.",
    levels: "NIVELES",
    levelsLabel: "Gamificación",
    levelsHint: "Racha, atributos por grupo y logros en Progreso. Solo lectura, sin presión.",
    streakFreezeLabel: "Tolerar un día perdido",
    streakFreezeHint: "Un único día (no de descanso) sin entrenar no corta la racha.",
    data: "DATOS",
    configFolder: "Carpeta de config",
    configFolderHint: "Tus JSON editables: rutina, equipo, perfil, logs.",
    openFolder: "ABRIR CARPETA",
    reload: "Recargar desde archivos",
    reloadHint: "Re-lee la config de los archivos al instante.",
    reloadBtn: "RECARGAR",
    replan: "Replanificar hoy",
    replanHint: "Vuelve a repartir las series desde ahora.",
    replanBtn: "REPLANIFICAR",
    resetSettings: "Restablecer ajustes",
    resetSettingsHint: "Horario, almuerzo y descanso a sus valores iniciales.",
    resetBtn: "RESTABLECER",
    resetAll: "Restablecer todo",
    resetAllHint: "Borra rutina, equipo y registros. Vuelve de fábrica.",
    resetAllBtn: "RESTABLECER TODO",
    railLabel: "CONFIGURACIÓN",
    railVersion: "VERSIÓN",
    railLang: "IDIOMA",
    groupPrefs: "PREFERENCIAS",
    groupSchedule: "AGENDA",
    groupCoach: "COACH Y NIVELES",
    groupData: "DATOS",
  },
  week: {
    title: "SEMANA",
    sub: "QUÉ HACÉS CADA DÍA",
    day: "Día",
    place: "Lugar",
    home: "CASA",
    office: "OFICINA",
  },
  equipment: {
    title: "EQUIPO",
    sub: "LO QUE TENÉS EN CASA",
    exercise: "EJERCICIO",
    exercises: "EJERCICIOS",
    inRoutines: "EN RUTINAS",
    custom: "PROPIO",
    placeholder: "NUEVO EQUIPO (EJ: ANILLAS)",
    add: "AGREGAR",
    removeAria: "Eliminar equipo",
    railLabel: "INVENTARIO",
    owned: "EN CASA",
    total: "CATÁLOGO",
    section: "EQUIPAMIENTO",
    addSection: "AGREGAR PROPIO",
  },
  routine: {
    title: "RUTINA",
    sub: "BIBLIOTECA DE ACTIVIDADES",
    noDayTypes: "No hay tipos de día. Restablecé desde Ajustes o creá uno.",
    dow: ["LUN", "MAR", "MIÉ", "JUE", "VIE", "SÁB", "DOM"],
    newDayType: "Nuevo",
    type: "TIPO",
    dayTypeNameAria: "Nombre del tipo de día",
    unassigned: "SIN ASIGNAR",
    deleteDayTypeAria: "Eliminar tipo de día",
    sets: "SERIES",
    noVolume: "SIN VOLUMEN",
    missing: "FALTA",
    balanced: "EQUILIBRADO",
    dayIntensityAria: "Intensidad del día",
    scheduleLabel: "HORARIO",
    scheduleGlobal: "GLOBAL",
    scheduleOwn: "PROPIO",
    scheduleStart: "EMPIEZA",
    scheduleDuration: "DURA",
    scheduleSpread: "Repartido en",
    restEvery: "descanso",
    exercises: "EJERCICIOS",
    muscles: "MÚSCULOS · TAP PRIM → SEC → OFF",
    emptyList: "Sin ejercicios. Agregá con el botón de abajo.",
    missingGearAria: "Te falta el equipo para este ejercicio",
    deskTag: "ESCRITORIO",
    missingGearTag: "FALTA EQUIPO",
    repsOrDurationAria: "Reps o duración",
    fewerSetsAria: "Menos series",
    moreSetsAria: "Más series",
    intensityAria: "Nivel de intensidad",
    removeAria: "Quitar",
    moveUpAria: "Subir en el orden",
    moveDownAria: "Bajar en el orden",
    editDayHint: "Editar la rutina de este día",
    renameHint: "Doble clic para renombrar",
    addExercise: "AGREGAR EJERCICIO",
    searchPlaceholder: "BUSCAR EJERCICIO…",
    cancel: "CANCELAR",
    createOwn: "CREAR PROPIO",
    add: "AGREGAR",
    noResultsPre: "No hay ejercicios para ",
    noneLeft: "No quedan ejercicios para agregar.",
    exerciseNamePlaceholder: "NOMBRE DEL EJERCICIO",
    muscleAria: "Músculo",
    measureAria: "Medida",
    measureReps: "Reps",
    measureHold: "Aguante",
    createAndAdd: "CREAR Y AGREGAR",
    // — agregar ejercicio (vista dedicada) —
    newExercise: "＋ NUEVO EJERCICIO",
    fromLibrary: "＋ DESDE BIBLIOTECA",
    unnamed: "Sin nombre",
    searchTitle: "Buscar",
    tabCreate: "CREAR",
    tabBrowse: "BUSCAR",
    addTo: "AGREGAR A:",
    pattern: "PATRÓN",
    metricRepsLabel: "REPETICIONES",
    metricTimeLabel: "SEGUNDOS",
    optReps: "reps",
    optTime: "tiempo",
    equipConditions: "EQUIPO Y CONDICIONES",
    needsSpace: "NECESITA ESPACIO",
    deskOk: "APTO ESCRITORIO",
    impact: "IMPACTO",
    pickMuscles: "ELEGÍ MÚSCULOS",
    missingPrefix: "FALTA",
    missName: "nombre",
    missPrimary: "1 primario",
    suggested: "SUGERIDO",
    apply: "APLICAR",
    patternWord: "Patrón",
    musclesWord: "músculos",
    musclesPickHint: "tocá un chip o el cuerpo · off → primario → secundario",
    // — biblioteca de actividades (rutinas de series + deportes externos) —
    routines: "RUTINAS",
    sports: "DEPORTES",
    sportShort: "DEPORTE",
    noSports: "Sin deportes. Sumá uno con ＋ DEPORTE.",
    modeLabel: "MODO",
    modeSpread: "REPARTIDO",
    modeBlock: "BLOQUE",
    sportEditKicker: "DEPORTE · EXTERNA",
    sportHint:
      "Un deporte se marca hecho, con duración e intensidad, en el Calendario. Acá solo lo definís.",
  },
  progress: {
    title: "PROGRESO",
    sub: "TU EVOLUCIÓN",
    emptyBefore: "Todavía no registraste series. Marcá ejercicios como",
    emptyDoneWord: "HECHO",
    emptyAfter: "y acá vas a ver tu evolución.",
    weekLabel: "ESTA SEMANA",
    streakLabel: "RACHA",
    activeLabel: "ACTIVOS",
    sets: "SERIES",
    day: "DÍA",
    days: "DÍAS",
    exercises: "EJERCICIOS",
    youreAt: "ESTÁS EN",
    since: "DESDE",
    nextLevel: "SIGUIENTE",
    maxLevel: "NIVEL MÁXIMO",
    ready: "LISTO:",
    last7days: "ÚLTIMOS 7 DÍAS",
    levelUp: "SUBIR",
    levelUpAria: "Subir de nivel este ejercicio",
  },
  levels: {
    streak: "RACHA",
    day: "DÍA",
    days: "DÍAS",
    bestEffort: "SIGUEN SUMANDO",
    sheet: "FICHA DE PERSONAJE",
    rank: "RANGO",
    lvl: "NIV",
    totalSets: "SERIES TOTALES",
    achievements: "LOGROS",
    locked: "BLOQUEADO",
    ach: {
      streak7: "RACHA DE 7",
      streak30: "RACHA DE 30",
      sets50: "50 SERIES",
      sets250: "250 SERIES",
      sets1000: "1000 SERIES",
      groupL3: "GRUPO NIV 3",
      groupL5: "GRUPO NIV 5",
    },
  },
  coach: {
    title: "COACH",
    subtitle: "TU ENTRENADOR",
    configureInSettings: "Configurar en Ajustes",
    week: "SEMANA",
    ready: "LISTO",
    setsSevenDays: "SERIES · 7D",
    balanced: "EQUILIBRADO",
    missing: "FALTA",
    noVolume: "SIN VOLUMEN",
    diagnostic: "DIAGNÓSTICO",
    conversations: "CONVERSACIONES",
    feasibility: "FACTIBILIDAD",
    progression: "PROGRESIÓN",
    balanceTitle: "BALANCE",
    activeDaysUnit: "días activos",
    history: "HISTORIAL",
    attention: "EL COACH NOTÓ",
    startersTitle: "O EMPEZÁ POR",
    alertInactive: "días sin entrenar",
    alertNeglected: "descuidado · 14d",
    alertVolumeDown: "vs. semana pasada",
    promptInactive: "Estuve {n} días sin entrenar, ayudame a retomar sin pasarme.",
    promptNeglected: "Vengo descuidando {g} hace dos semanas. Ajustá mi semana para cubrir ese grupo.",
    promptVolumeDown: "Mi volumen bajó {n}% respecto a la semana pasada. ¿Cómo lo recupero?",
    promptFitVolume: "No me entra el volumen, ajustalo para que entre en mi horario",
    promptLevelUpPrefix: "¿Estoy listo para subir de nivel en",
    promptBalance: "Equilibrá los grupos musculares de mi rutina",
    new: "NUEVA",
    noChatsYet: "SIN CHARLAS TODAVÍA",
    resumeInClaudeCode: "Retomar en Claude Code",
    claudeCodeReadOnly: "CLAUDE CODE · SOLO LECTURA",
    emptyOrUnreadable: "SESIÓN VACÍA O ILEGIBLE",
    conversationLivesInClaudeCode: "LA CONVERSACIÓN VIVE EN CLAUDE CODE",
    resumeInClaudeCodeBtn: "RETOMAR EN CLAUDE CODE",
    onboardingTitle: "¿Qué querés lograr?",
    onboardingBody:
      "Te propongo cambios en tu rutina, semana o equipo — y los aprobás antes de aplicar.",
    starters: [
      "Armá mi semana para mi objetivo",
      "Subí mi volumen sin pasarme del horario",
      "Tengo una molestia hoy, adaptá la rutina",
    ],
    thinking: "PENSANDO…",
    inputPlaceholder: "Hablá con el coach…",
    send: "ENVIAR",
    proposedChanges: "CAMBIOS PROPUESTOS",
    apply: "APLICAR",
    discard: "DESCARTAR",
  },
  body: {
    title: "MAPA MUSCULAR",
    coverage: "COBERTURA",
    open: "VER CUERPO",
    front: "FRENTE",
    back: "ESPALDA",
    load: "CARGA",
    sets: "series",
    noExercises: "sin ejercicios que lo trabajen",
    levelNone: "SIN CARGA",
    levelLow: "BAJA",
    levelMid: "MEDIA",
    levelHigh: "ALTA",
    aggregate: "AGREGADO · TODO EL DÍA",
    isolated: "AISLADO",
    allDay: "TODO EL DÍA",
    hoverHint: "PASÁ EL MOUSE PARA AISLAR · CLIC PARA FIJAR",
    primary: "PRIMARIO",
    secondary: "SECUNDARIO",
    untrained: "sin trabajar",
    gapSub: "Ningún ejercicio las cubre hoy",
    add: "AGREGAR",
    coverageDay: "COBERTURA DEL DÍA",
    live: "LIVE",
    musclesNew: "MÚSCULOS · NUEVO",
    spreadHint: "CARGA REPARTIDA EN TODO EL DÍA",
    pickHint: "TOCÁ UN MÚSCULO PARA ASIGNARLO",
    closesLegs: "Cierra el hueco de Piernas",
    stillLegs: "Todavía falta Piernas",
    dayCoverage: "Cobertura del día",
    groupsAtCreate: "GRUPOS AL CREAR",
    legsUncovered: "PIERNAS SIN CUBRIR",
    groupsCovered: "GRUPOS CUBIERTOS",
    groups: "GRUPOS",
    regions: {
      chest: "Pecho",
      back: "Espalda",
      shoulders: "Hombros",
      arms: "Brazos",
      core: "Core",
      legs: "Piernas",
    },
    muscleNames: {
      chest: "Pecho",
      abs: "Abdomen",
      obliques: "Oblicuos",
      biceps: "Bíceps",
      triceps: "Tríceps",
      forearm: "Antebrazo",
      "front-deltoids": "Hombro frontal",
      "back-deltoids": "Hombro posterior",
      trapezius: "Trapecio",
      "upper-back": "Espalda alta",
      "lower-back": "Espalda baja",
      quadriceps: "Cuádriceps",
      hamstring: "Isquios",
      gluteal: "Glúteo",
      calves: "Pantorrillas",
      adductor: "Aductor",
      abductors: "Abductor",
    },
  },
  shell: {
    online: "EN LÍNEA",
    relay: "PAUSA ACTIVA RELAY",
  },
  cal: {
    week: "SEMANA",
    month: "MES",
    months: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
    prev: "Mes anterior",
    next: "Mes siguiente",
    today: "HOY",
    dayPlan: "PLAN DEL DÍA",
    useWeekly: "Usar patrón semanal",
    overrideTag: "EXCEPCIÓN",
    weeklyDefault: "patrón semanal",
    pickDate: "Elegí un día para planearlo",
  },
  entreno: {
    title: "ENTRENO",
    sub: "SESIONES Y ADAPTACIÓN",
    railLabel: "MÓDULO ENTRENO",
    railSessions: "SESIONES",
    railAssigned: "EN LA SEMANA",
    newStructured: "＋ ESTRUCTURADA",
    newExternal: "＋ EXTERNA",
    weekTitle: "SEMANA",
    weekHint: "ASIGNÁ UNA SESIÓN A CADA DÍA",
    outing: "SALIDA",
    none: "—",
    sessionsTitle: "SESIONES",
    noSessions: "Sin sesiones. Creá una estructurada o externa.",
    delete: "Eliminar sesión",
    structured: "ESTRUCTURADA",
    external: "EXTERNA",
    nameLabel: "NOMBRE",
    startLabel: "EMPIEZA",
    modality: "MODALIDAD",
    location: "LUGAR",
    modalities: { calisthenics: "Calistenia", strength: "Fuerza", sport: "Deporte", cardio: "Cardio" },
    locations: { home: "Casa", away: "Afuera" },
    duration: "DURACIÓN",
    intensity: "INTENSIDAD",
    min: "MIN",
    exercises: "EJERCICIOS",
    addExercise: "＋ AÑADIR EJERCICIO",
    noItems: "Sin ejercicios todavía.",
    removeItem: "Quitar ejercicio",
    markDone: "REGISTRAR HECHA",
    markMissed: "NO HECHA",
    reasonTitle: "¿POR QUÉ NO?",
    reasons: { enfermo: "Enfermo", lesionado: "Lesionado", ocupado: "Ocupado", viajando: "Viajando" },
    adaptTitle: "ADAPTACIÓN",
    adaptKindRest: "DESCANSO",
    adaptKindMobility: "MOVILIDAD",
    adaptKindSubstitute: "SUSTITUCIÓN",
    addsLoad: "SUMA CARGA",
    noLoad: "SIN CARGA COMPENSATORIA",
    skillDropped: "SKILL NO SUSTITUIDA",
    circuit: "CIRCUITO EN CASA",
    emptyCircuit: "Sin circuito — priorizá recuperar.",
    status: { done: "HECHA HOY", skipped: "SALTADA HOY" },
  },
  // CALENDARIO — la agenda (semana/mes): dónde ves qué toca cada día y lo marcás.
  // Reusa t.routine.dow, t.week.*, t.cal.* y t.entreno.* donde ya existen.
  calendar: {
    title: "CALENDARIO",
    sub: "TU AGENDA — QUÉ TOCA CADA DÍA",
    weekOf: "SEMANA DEL",
    agenda: "AGENDA",
    dayType: "TIPO DE DÍA",
    pending: "PENDIENTE",
    pickDay: "Elegí un día con salida para marcarlo",
    todayOnly: "Solo el día de hoy se puede marcar",
    outingOn: "SALIDA",
  },
};

export type Dict = typeof es;

const en: Dict = {
  nav: {
    coach: "COACH",
    today: "TODAY",
    calendar: "CALENDAR",
    routine: "ROUTINE",
    week: "WEEK",
    equipment: "GEAR",
    progress: "PROGRESS",
    entreno: "TRAINING",
    social: "FRIENDS",
    settings: "SETTINGS",
    themeLight: "LIGHT THEME",
    themeDark: "DARK THEME",
  },
  // Social / league layer (F4).
  social: {
    title: "FRIENDS",
    sub: "LEAGUE",
    leagueSoon: "League — coming soon",
    season: "SEASON",
    noCloud: "Cloud not configured. Set VITE_CLERK_PUBLISHABLE_KEY and VITE_CONVEX_URL to enable the league.",
    signInHeading: "Enter the league",
    signInSub: "Compare your weekly effort with friends. Derived stats only — your raw logs never leave the device.",
    myGroups: "My groups",
    noGroups: "You're not in any group yet. Create one or join with a code.",
    createGroup: "Create group",
    groupNamePlaceholder: "Group name",
    create: "Create",
    joinGroup: "Join by code",
    codePlaceholder: "Invite code",
    join: "Join",
    inviteCode: "Code",
    selectGroupHint: "Pick a group to see its table.",
    publish: "Publish my stats",
    publishing: "Publishing…",
    published: "Published",
    refresh: "Update",
    autoPublish: "Auto-published",
    leave: "Leave group",
    emptyStandings: "No one has published stats this season yet. Be the first.",
    colRank: "#",
    colAthlete: "ATHLETE",
    colForma: "FORM",
    colAdherence: "ADHERENCE",
    colEffort: "EFFORT",
    colStreak: "STREAK",
    colLevel: "LEVEL",
    sortLabel: "SORT",
    sortWeek: "WEEK",
    sortForma: "FORM",
    you: "YOU",
    loading: "Loading…",
    routines: "Group routines",
    shareRoutine: "Share a routine",
    chooseRoutine: "Choose a routine…",
    share: "Share",
    copy: "Copy",
    copied: "Copied ✓",
    unshare: "Remove",
    noRoutines: "No routines shared yet. Share one of yours.",
    sharedBy: "by",
    mineTag: "YOURS",
    routineSets: "ex.",
    badRoutine: "Couldn't read that routine.",
  },
  // Group challenge (F4) — one challenge per group, goal + check-ins per athlete.
  challenge: {
    label: "Group challenge",
    none: "This group has no active challenge. Create one for everyone.",
    createTitle: "Create challenge",
    titlePlaceholder: "Challenge title",
    targetDateLabel: "Target date",
    create: "Create challenge",
    daysLeft: "days left",
    dayLeft: "day left",
    lastDay: "last day",
    finished: "Finished",
    delete: "Delete challenge",
    myGoal: "My goal",
    goalDescPlaceholder: "What do you want to achieve?",
    metricOptional: "Metric (optional)",
    metricLabelPlaceholder: "Label (e.g. Weight)",
    metricUnitPlaceholder: "Unit",
    metricStartPlaceholder: "Start",
    metricTargetPlaceholder: "Target",
    saveGoal: "Save goal",
    saved: "Saved",
    logProgress: "Log progress",
    currentValuePlaceholder: "Current value",
    pctPlaceholder: "% (0-100)",
    notePlaceholder: "Note (optional)",
    checkin: "Log",
    noEntries: "No one has set a goal yet. Set yours.",
    noGoal: "No goal",
    progress: "Progress",
    lastCheckin: "last check-in",
  },
  muscle: { pull: "Pull", push: "Push", core: "Core", legs: "Legs" },
  context: { desk: "Desk", space: "Needs space" },
  feasibility: {
    all: "ALL FITS",
    wontFit: "WON'T FIT",
    empty: "EMPTY",
    hint: "They don't fit your work window. Trim volume or widen your hours.",
  },
  actions: {
    done: "DONE",
    later: "LATER",
    skip: "SKIP TODAY",
    skipped: "SKIPPED TODAY",
  },
  today: {
    title: "TODAY",
    weekdays: ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"],
    rest: "REST",
    restTitle: "Rest day",
    restSub: "Recover today · back at it tomorrow",
    restScreen: "REST · RECOVERY",
    restStatus: "SYSTEM AT REST",
    restProtocol: "PROTOCOL",
    restProtocolBody: "No sets scheduled. Muscle grows in the pause.",
    restTip1: "Hydrate and move gently",
    restTip2: "Sleep your hours",
    restNext: "NEXT SESSION",
    restNextValue: "TOMORROW",
    setsDone: "SETS DONE",
    loadToday: "TODAY'S LOAD",
    theDay: "THE DAY",
    sets: "SETS",
    now: "NOW",
    in: "IN",
    min: "MIN",
    next: "NEXT",
    reps: "REPS",
    minutes: "MINUTES",
    hours: "HOURS",
    stPending: "PENDING",
    stDone: "DONE",
    stSkipped: "SKIPPED",
    stNow: "NOW",
    stNext: "NEXT",
    outOfHours: "OUTSIDE HOURS · THEY'LL SPREAD AGAIN TOMORROW",
    noRoutine: "NO EXERCISES — BUILD YOUR ROUTINE",
    logFree: "＋ LOG SET",
    logFreeTitle: "LOG A FREE SET",
    logPick: "PICK EXERCISE",
    logVariant: "VARIANT",
    logCancel: "CANCEL",
    logConfirm: "LOG",
    logged: "LOGGED",
    entrenoSession: "TODAY'S SESSION",
    entrenoWindow: "WINDOW",
  },
  focus: {
    label: "FOCUS",
    on: "IN FOCUS",
    sub: "NO PINGS",
    remaining: "MIN LEFT",
    start: "Focus mode",
    hint: "Silences reminders for a while. Sets stay scheduled.",
    end: "END FOCUS",
    cancel: "CANCEL",
  },
  panel: {
    noSets: "No sets",
    next: "NEXT",
    now: "NOW",
    min: "MIN",
    h: "H",
    reps: "REPS",
  },
  toast: {
    now: "NOW",
    reps: "REPS",
  },
  update: {
    label: "UPDATE",
    newVersion: "New version",
    downloading: "DOWNLOADING",
    ready: "READY TO INSTALL",
    failed: "DOWNLOAD FAILED — RETRY",
    install: "UPDATE & RESTART",
    retry: "RETRY",
    // — manual check in Settings —
    section: "UPDATES",
    checkLabel: "Check for updates",
    checkHint: "Looks for a newer published version.",
    checkBtn: "CHECK",
    currentVersion: "Current version",
    stChecking: "CHECKING…",
    stUpToDate: "YOU'RE UP TO DATE",
    stAvailable: "A NEW VERSION IS AVAILABLE",
    stError: "COULDN'T CHECK",
  },
  settings: {
    title: "SETTINGS",
    sub: "CONFIGURATION",
    appearance: "APPEARANCE",
    theme: "Theme",
    modeLight: "Light",
    modeDark: "Dark",
    modeSystem: "System",
    accent: "Accent",
    language: "LANGUAGE",
    languageLabel: "App language",
    panelSection: "FLOATING PANEL",
    showPanel: "Show panel",
    showPanelHint: "Always-visible mini-window with your next exercise.",
    notifications: "NOTIFICATIONS",
    notifLabel: "microset reminders",
    notifHint: "Pings you when a set is due.",
    snoozeLabel: "Snooze time",
    focusSection: "FOCUS",
    work: "WORK HOURS",
    start: "Start",
    end: "End",
    lunch: "LUNCH",
    from: "From",
    to: "To",
    minRest: "MINIMUM REST",
    between: "Between sets",
    coach: "COACH",
    provider: "Provider",
    model: "Model",
    modelHint: "Needs ANTHROPIC_API_KEY in the environment.",
    endpoint: "Endpoint",
    endpointHint: "OpenAI-compatible (Ollama / LM Studio).",
    goals: "GOALS",
    goalsPh: "E.g. my first muscle-up, 12 pull-ups, lose fat…",
    diet: "DIET",
    dietPh: "E.g. slight surplus, ~140 g of protein…",
    constraints: "CONSTRAINTS",
    constraintsPh: "E.g. right shoulder niggle, no jumping…",
    demo: "DEMO MODE",
    demoLabel: "Enable demo mode",
    demoHint: "Schedules sets from now, ignoring your hours, to try the app.",
    modules: "MODULES",
    entrenoModuleLabel: "Training",
    entrenoModuleHint: "Add outings (BJJ, gym, runs) to your week in Rutina, with adaptive rescheduling if you miss one.",
    socialModuleLabel: "Friends",
    socialModuleHint: "Optional weekly league with friends. Derived effort only; your raw logs never leave the device.",
    syncSection: "CLOUD",
    syncLabel: "Sync across devices",
    syncHint: "Mirrors your config (routine, gear, exercises, settings) via the cloud so it matches on another device. Opt-in; requires signing in under Friends. Your logs don't sync yet.",
    levels: "LEVELS",
    levelsLabel: "Gamification",
    levelsHint: "Streak, per-group attributes and achievements in Progress. Read-only, no pressure.",
    streakFreezeLabel: "Tolerate one missed day",
    streakFreezeHint: "A single non-rest day without training won't break the streak.",
    data: "DATA",
    configFolder: "Config folder",
    configFolderHint: "Your editable JSON: routine, gear, profile, logs.",
    openFolder: "OPEN FOLDER",
    reload: "Reload from files",
    reloadHint: "Re-reads the config from the files instantly.",
    reloadBtn: "RELOAD",
    replan: "Replan today",
    replanHint: "Spreads the sets again from now.",
    replanBtn: "REPLAN",
    resetSettings: "Reset settings",
    resetSettingsHint: "Hours, lunch and rest back to their defaults.",
    resetBtn: "RESET",
    resetAll: "Reset everything",
    resetAllHint: "Wipes routine, gear and logs. Back to factory.",
    resetAllBtn: "RESET ALL",
    railLabel: "CONFIGURATION",
    railVersion: "VERSION",
    railLang: "LANGUAGE",
    groupPrefs: "PREFERENCES",
    groupSchedule: "SCHEDULE",
    groupCoach: "COACH & LEVELS",
    groupData: "DATA",
  },
  week: {
    title: "WEEK",
    sub: "WHAT YOU DO EACH DAY",
    day: "Day",
    place: "Place",
    home: "HOME",
    office: "OFFICE",
  },
  equipment: {
    title: "GEAR",
    sub: "WHAT YOU HAVE AT HOME",
    exercise: "EXERCISE",
    exercises: "EXERCISES",
    inRoutines: "IN ROUTINES",
    custom: "CUSTOM",
    placeholder: "NEW GEAR (E.G. RINGS)",
    add: "ADD",
    removeAria: "Remove gear",
    railLabel: "INVENTORY",
    owned: "AT HOME",
    total: "CATALOG",
    section: "EQUIPMENT",
    addSection: "ADD CUSTOM",
  },
  routine: {
    title: "ROUTINE",
    sub: "ACTIVITY LIBRARY",
    noDayTypes: "No day types. Reset from Settings or create one.",
    dow: ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"],
    newDayType: "New",
    type: "TYPE",
    dayTypeNameAria: "Day type name",
    unassigned: "UNASSIGNED",
    deleteDayTypeAria: "Delete day type",
    sets: "SETS",
    noVolume: "NO VOLUME",
    missing: "MISSING",
    balanced: "BALANCED",
    dayIntensityAria: "Day intensity",
    scheduleLabel: "SCHEDULE",
    scheduleGlobal: "GLOBAL",
    scheduleOwn: "OWN",
    scheduleStart: "STARTS",
    scheduleDuration: "LASTS",
    scheduleSpread: "Spread across",
    restEvery: "rest",
    exercises: "EXERCISES",
    muscles: "MUSCLES · TAP PRIM → SEC → OFF",
    emptyList: "No exercises. Add one with the button below.",
    missingGearAria: "You're missing the gear for this exercise",
    deskTag: "DESK",
    missingGearTag: "MISSING GEAR",
    repsOrDurationAria: "Reps or duration",
    fewerSetsAria: "Fewer sets",
    moreSetsAria: "More sets",
    intensityAria: "Intensity level",
    removeAria: "Remove",
    moveUpAria: "Move up in order",
    moveDownAria: "Move down in order",
    editDayHint: "Edit this day's routine",
    renameHint: "Double-click to rename",
    addExercise: "ADD EXERCISE",
    searchPlaceholder: "SEARCH EXERCISE…",
    cancel: "CANCEL",
    createOwn: "CREATE OWN",
    add: "ADD",
    noResultsPre: "No exercises for ",
    noneLeft: "No exercises left to add.",
    exerciseNamePlaceholder: "EXERCISE NAME",
    muscleAria: "Muscle",
    measureAria: "Measure",
    measureReps: "Reps",
    measureHold: "Hold",
    createAndAdd: "CREATE & ADD",
    // — add exercise (dedicated view) —
    newExercise: "＋ NEW EXERCISE",
    fromLibrary: "＋ FROM LIBRARY",
    unnamed: "Untitled",
    searchTitle: "Search",
    tabCreate: "CREATE",
    tabBrowse: "BROWSE",
    addTo: "ADD TO:",
    pattern: "PATTERN",
    metricRepsLabel: "REPS",
    metricTimeLabel: "SECONDS",
    optReps: "reps",
    optTime: "time",
    equipConditions: "EQUIPMENT & CONDITIONS",
    needsSpace: "NEEDS SPACE",
    deskOk: "DESK-FRIENDLY",
    impact: "IMPACT",
    pickMuscles: "PICK MUSCLES",
    missingPrefix: "NEED",
    missName: "name",
    missPrimary: "1 primary",
    suggested: "SUGGESTED",
    apply: "APPLY",
    patternWord: "Pattern",
    musclesWord: "muscles",
    musclesPickHint: "tap a chip or the body · off → primary → secondary",
    // — activity library (series routines + external sports) —
    routines: "ROUTINES",
    sports: "SPORTS",
    sportShort: "SPORT",
    noSports: "No sports yet. Add one with ＋ SPORT.",
    modeLabel: "MODE",
    modeSpread: "SPREAD",
    modeBlock: "BLOCK",
    sportEditKicker: "SPORT · EXTERNAL",
    sportHint:
      "A sport is marked done, with duration and intensity, in the Calendar. Here you just define it.",
  },
  progress: {
    title: "PROGRESS",
    sub: "YOUR EVOLUTION",
    emptyBefore: "You haven't logged any sets yet. Mark exercises as",
    emptyDoneWord: "DONE",
    emptyAfter: "and you'll see your evolution here.",
    weekLabel: "THIS WEEK",
    streakLabel: "STREAK",
    activeLabel: "ACTIVE",
    sets: "SETS",
    day: "DAY",
    days: "DAYS",
    exercises: "EXERCISES",
    youreAt: "YOU'RE AT",
    since: "SINCE",
    nextLevel: "NEXT",
    maxLevel: "MAX LEVEL",
    ready: "READY:",
    last7days: "LAST 7 DAYS",
    levelUp: "LEVEL UP",
    levelUpAria: "Level up this exercise",
  },
  levels: {
    streak: "STREAK",
    day: "DAY",
    days: "DAYS",
    bestEffort: "STILL COUNTING",
    sheet: "CHARACTER SHEET",
    rank: "RANK",
    lvl: "LVL",
    totalSets: "TOTAL SETS",
    achievements: "ACHIEVEMENTS",
    locked: "LOCKED",
    ach: {
      streak7: "7-DAY STREAK",
      streak30: "30-DAY STREAK",
      sets50: "50 SETS",
      sets250: "250 SETS",
      sets1000: "1000 SETS",
      groupL3: "GROUP LVL 3",
      groupL5: "GROUP LVL 5",
    },
  },
  coach: {
    title: "COACH",
    subtitle: "YOUR TRAINER",
    configureInSettings: "Configure in Settings",
    week: "WEEK",
    ready: "READY",
    setsSevenDays: "SETS · 7D",
    balanced: "BALANCED",
    missing: "MISSING",
    noVolume: "NO VOLUME",
    diagnostic: "READOUT",
    conversations: "CONVERSATIONS",
    feasibility: "FEASIBILITY",
    progression: "PROGRESSION",
    balanceTitle: "BALANCE",
    activeDaysUnit: "active days",
    history: "HISTORY",
    attention: "WHAT I NOTICED",
    startersTitle: "OR START WITH",
    alertInactive: "days without training",
    alertNeglected: "neglected · 14d",
    alertVolumeDown: "vs last week",
    promptInactive: "I've been {n} days without training — help me ease back in.",
    promptNeglected: "I've been neglecting {g} for two weeks. Adjust my week to cover that group.",
    promptVolumeDown: "My volume dropped {n}% vs last week. How do I get it back?",
    promptFitVolume: "My volume doesn't fit, adjust it so it fits my schedule",
    promptLevelUpPrefix: "Am I ready to level up on",
    promptBalance: "Balance the muscle groups in my routine",
    new: "NEW",
    noChatsYet: "NO CHATS YET",
    resumeInClaudeCode: "Resume in Claude Code",
    claudeCodeReadOnly: "CLAUDE CODE · READ ONLY",
    emptyOrUnreadable: "EMPTY OR UNREADABLE SESSION",
    conversationLivesInClaudeCode: "THE CONVERSATION LIVES IN CLAUDE CODE",
    resumeInClaudeCodeBtn: "RESUME IN CLAUDE CODE",
    onboardingTitle: "What do you want to achieve?",
    onboardingBody:
      "I'll propose changes to your routine, week, or equipment — and you approve them before they apply.",
    starters: [
      "Build my week for my goal",
      "Increase my volume without overrunning my schedule",
      "I have a niggle today, adapt the routine",
    ],
    thinking: "THINKING…",
    inputPlaceholder: "Talk to the coach…",
    send: "SEND",
    proposedChanges: "PROPOSED CHANGES",
    apply: "APPLY",
    discard: "DISCARD",
  },
  body: {
    title: "MUSCLE MAP",
    coverage: "COVERAGE",
    open: "VIEW BODY",
    front: "FRONT",
    back: "BACK",
    load: "LOAD",
    sets: "sets",
    noExercises: "no exercises work it",
    levelNone: "NO LOAD",
    levelLow: "LOW",
    levelMid: "MED",
    levelHigh: "HIGH",
    aggregate: "AGGREGATE · ALL DAY",
    isolated: "ISOLATED",
    allDay: "ALL DAY",
    hoverHint: "HOVER TO ISOLATE · CLICK TO PIN",
    primary: "PRIMARY",
    secondary: "SECONDARY",
    untrained: "untrained",
    gapSub: "No exercise covers them today",
    add: "ADD",
    coverageDay: "DAY COVERAGE",
    live: "LIVE",
    musclesNew: "MUSCLES · NEW",
    spreadHint: "LOAD SPREAD ACROSS THE DAY",
    pickHint: "TAP A MUSCLE TO ASSIGN IT",
    closesLegs: "Closes the Legs gap",
    stillLegs: "Legs still missing",
    dayCoverage: "Day coverage",
    groupsAtCreate: "GROUPS ON CREATE",
    legsUncovered: "LEGS NOT COVERED",
    groupsCovered: "GROUPS COVERED",
    groups: "GROUPS",
    regions: {
      chest: "Chest",
      back: "Back",
      shoulders: "Shoulders",
      arms: "Arms",
      core: "Core",
      legs: "Legs",
    },
    muscleNames: {
      chest: "Chest",
      abs: "Abs",
      obliques: "Obliques",
      biceps: "Biceps",
      triceps: "Triceps",
      forearm: "Forearm",
      "front-deltoids": "Front delts",
      "back-deltoids": "Rear delts",
      trapezius: "Trapezius",
      "upper-back": "Upper back",
      "lower-back": "Lower back",
      quadriceps: "Quads",
      hamstring: "Hamstrings",
      gluteal: "Glutes",
      calves: "Calves",
      adductor: "Adductor",
      abductors: "Abductors",
    },
  },
  shell: {
    online: "ONLINE",
    relay: "ACTIVE BREAK RELAY",
  },
  cal: {
    week: "WEEK",
    month: "MONTH",
    months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    prev: "Previous month",
    next: "Next month",
    today: "TODAY",
    dayPlan: "DAY PLAN",
    useWeekly: "Use weekly pattern",
    overrideTag: "EXCEPTION",
    weeklyDefault: "weekly pattern",
    pickDate: "Pick a day to plan it",
  },
  entreno: {
    title: "TRAINING",
    sub: "SESSIONS & ADAPTATION",
    railLabel: "TRAINING MODULE",
    railSessions: "SESSIONS",
    railAssigned: "IN THE WEEK",
    newStructured: "＋ STRUCTURED",
    newExternal: "＋ EXTERNAL",
    weekTitle: "WEEK",
    weekHint: "ASSIGN A SESSION TO EACH DAY",
    outing: "OUTING",
    none: "—",
    sessionsTitle: "SESSIONS",
    noSessions: "No sessions yet. Create a structured or external one.",
    delete: "Delete session",
    structured: "STRUCTURED",
    external: "EXTERNAL",
    nameLabel: "NAME",
    startLabel: "STARTS",
    modality: "MODALITY",
    location: "LOCATION",
    modalities: { calisthenics: "Calisthenics", strength: "Strength", sport: "Sport", cardio: "Cardio" },
    locations: { home: "Home", away: "Away" },
    duration: "DURATION",
    intensity: "INTENSITY",
    min: "MIN",
    exercises: "EXERCISES",
    addExercise: "＋ ADD EXERCISE",
    noItems: "No exercises yet.",
    removeItem: "Remove exercise",
    markDone: "LOG DONE",
    markMissed: "NOT DONE",
    reasonTitle: "WHY NOT?",
    reasons: { enfermo: "Sick", lesionado: "Injured", ocupado: "Busy", viajando: "Traveling" },
    adaptTitle: "ADAPTATION",
    adaptKindRest: "REST",
    adaptKindMobility: "MOBILITY",
    adaptKindSubstitute: "SUBSTITUTION",
    addsLoad: "ADDS LOAD",
    noLoad: "NO COMPENSATORY LOAD",
    skillDropped: "SKILL NOT SUBSTITUTED",
    circuit: "HOME CIRCUIT",
    emptyCircuit: "No circuit — prioritize recovery.",
    status: { done: "DONE TODAY", skipped: "SKIPPED TODAY" },
  },
  calendar: {
    title: "CALENDAR",
    sub: "YOUR AGENDA — WHAT'S ON EACH DAY",
    weekOf: "WEEK OF",
    agenda: "AGENDA",
    dayType: "DAY TYPE",
    pending: "PENDING",
    pickDay: "Pick a day with an outing to mark it",
    todayOnly: "Only today can be marked",
    outingOn: "OUTING",
  },
};

export const STRINGS: Record<Lang, Dict> = { es, en };

/** Default language from the OS/browser locale; Spanish locales → es, else en. */
export function detectLang(): Lang {
  if (typeof navigator !== "undefined" && navigator.language?.toLowerCase().startsWith("es"))
    return "es";
  return "en";
}
