/**
 * App i18n dictionary (EN/ES). Store-free so the Zustand store can import the
 * Lang type + detector without a cycle. `es` is the source of truth; `en` must
 * match its shape (enforced by the `Dict` type).
 */

export type Lang = "es" | "en";

const es = {
  nav: {
    coach: "COACH",
    today: "HOY",
    routine: "RUTINA",
    week: "SEMANA",
    equipment: "EQUIPO",
    progress: "PROGRESO",
    settings: "AJUSTES",
    themeLight: "TEMA CLARO",
    themeDark: "TEMA OSCURO",
  },
  muscle: { pull: "Tirón", push: "Empuje", core: "Core", legs: "Piernas" },
  context: { desk: "De escritorio", space: "Necesita espacio" },
  today: {
    title: "HOY",
    weekdays: ["LUNES", "MARTES", "MIÉRCOLES", "JUEVES", "VIERNES", "SÁBADO", "DOMINGO"],
    rest: "DESCANSO",
    restTitle: "Día de descanso",
    restSub: "Hoy toca recuperar · mañana seguimos",
    setsDone: "SERIES HECHAS",
    loadToday: "CARGA DE HOY",
    theDay: "EL DÍA",
    sets: "SERIES",
    now: "AHORA",
    in: "EN",
    min: "MIN",
    next: "PRÓXIMA",
    reps: "REPS",
    minutes: "MINUTOS",
    hours: "HORAS",
    done: "HECHO",
    snooze: "POSPONER",
    notNow: "AHORA NO",
    stPending: "PENDIENTE",
    stDone: "HECHO",
    stSkipped: "SALTADO",
    stNow: "AHORA",
    stNext: "PRÓXIMA",
    stWontFit: "NO ENTRA",
    outOfHours: "FUERA DE HORARIO · MAÑANA SE REPARTEN DE NUEVO",
    noRoutine: "SIN EJERCICIOS — ARMÁ TU RUTINA",
  },
  panel: {
    noSets: "Sin series",
    next: "PRÓXIMA",
    now: "AHORA",
    done: "HECHO",
    notNow: "AHORA NO",
    min: "MIN",
    h: "H",
    reps: "REPS",
  },
  toast: {
    now: "AHORA",
    done: "HECHO",
    snooze: "POSPONER",
    notNow: "AHORA NO",
    reps: "REPS",
  },
  update: {
    label: "ACTUALIZACIÓN",
    newVersion: "Nueva versión",
    downloading: "DESCARGANDO",
    ready: "LISTA PARA INSTALAR",
    failed: "FALLÓ LA DESCARGA — REINTENTÁ",
    install: "ACTUALIZAR Y REINICIAR",
    retry: "REINTENTAR",
  },
  settings: {
    title: "AJUSTES",
    sub: "CONFIGURACIÓN",
    appearance: "APARIENCIA",
    theme: "Tema",
    modeLight: "Claro",
    modeDark: "Oscuro",
    modeSystem: "Sistema",
    accent: "Acento",
    language: "IDIOMA",
    languageLabel: "Idioma de la app",
    panelSection: "PANEL FLOTANTE",
    showPanel: "Mostrar panel",
    showPanelHint: "Mini-ventana siempre visible con el próximo ejercicio.",
    notifications: "NOTIFICACIONES",
    notifLabel: "Avisos de microset",
    notifHint: "Te avisa cuando toca una serie.",
    snoozeLabel: "Tiempo de posponer",
    work: "HORARIO LABORAL",
    start: "Inicio",
    end: "Fin",
    lunch: "ALMUERZO",
    from: "Desde",
    to: "Hasta",
    minRest: "DESCANSO MÍNIMO",
    between: "Entre series",
    coach: "COACH",
    provider: "Proveedor",
    model: "Modelo",
    modelHint: "Necesita ANTHROPIC_API_KEY en el entorno.",
    endpoint: "Endpoint",
    endpointHint: "OpenAI-compatible (Ollama / LM Studio).",
    goals: "OBJETIVOS",
    goalsPh: "Ej: mi primer muscle-up, 12 dominadas, bajar grasa…",
    diet: "DIETA",
    dietPh: "Ej: superávit leve, ~140 g de proteína…",
    constraints: "RESTRICCIONES",
    constraintsPh: "Ej: molestia en hombro derecho, sin saltos…",
    demo: "MODO DEMO",
    demoLabel: "Activar modo demo",
    demoHint: "Agenda series desde ahora, ignorando tu horario, para probar la app.",
    data: "DATOS",
    configFolder: "Carpeta de config",
    configFolderHint: "Tus JSON editables: rutina, equipo, perfil, logs.",
    openFolder: "ABRIR CARPETA",
    reload: "Recargar desde archivos",
    reloadHint: "Re-lee la config de los archivos al instante.",
    reloadBtn: "RECARGAR",
    replan: "Replanificar hoy",
    replanHint: "Vuelve a repartir las series desde ahora.",
    replanBtn: "REPLANIFICAR",
    resetSettings: "Restablecer ajustes",
    resetSettingsHint: "Horario, almuerzo y descanso a sus valores iniciales.",
    resetBtn: "RESTABLECER",
    resetAll: "Restablecer todo",
    resetAllHint: "Borra rutina, equipo y registros. Vuelve de fábrica.",
    resetAllBtn: "RESTABLECER TODO",
  },
  week: {
    title: "SEMANA",
    sub: "QUÉ HACÉS CADA DÍA",
    day: "Día",
    place: "Lugar",
    home: "CASA",
    office: "OFICINA",
  },
  equipment: {
    title: "EQUIPO",
    sub: "LO QUE TENÉS EN CASA",
    exercise: "EJERCICIO",
    exercises: "EJERCICIOS",
    inRoutines: "EN RUTINAS",
    custom: "PROPIO",
    placeholder: "NUEVO EQUIPO (EJ: ANILLAS)",
    add: "AGREGAR",
    removeAria: "Eliminar equipo",
  },
  routine: {
    title: "RUTINA",
    sub: "ARMÁ CADA TIPO DE DÍA",
    noDayTypes: "No hay tipos de día. Restablecé desde Ajustes o creá uno.",
    dow: ["LUN", "MAR", "MIÉ", "JUE", "VIE", "SÁB", "DOM"],
    newDayType: "Nuevo",
    type: "TIPO",
    dayTypeNameAria: "Nombre del tipo de día",
    unassigned: "SIN ASIGNAR",
    deleteDayTypeAria: "Eliminar tipo de día",
    sets: "SERIES",
    fitHint: "Recortá volumen o ampliá tu horario.",
    empty: "VACÍO",
    fits: "ENTRA ✓",
    fitsCount: "ENTRAN",
    noVolume: "SIN VOLUMEN",
    missing: "FALTA",
    balanced: "EQUILIBRADO",
    dayIntensityAria: "Intensidad del día",
    exercises: "EJERCICIOS",
    muscles: "MÚSCULOS · TAP PRIM → SEC → OFF",
    emptyList: "Sin ejercicios. Agregá con el botón de abajo.",
    missingGearAria: "Te falta el equipo para este ejercicio",
    deskTag: "ESCRITORIO",
    missingGearTag: "FALTA EQUIPO",
    repsOrDurationAria: "Reps o duración",
    fewerSetsAria: "Menos series",
    moreSetsAria: "Más series",
    intensityAria: "Nivel de intensidad",
    removeAria: "Quitar",
    moveUpAria: "Subir en el orden",
    moveDownAria: "Bajar en el orden",
    editDayHint: "Editar la rutina de este día",
    renameHint: "Doble clic para renombrar",
    addExercise: "AGREGAR EJERCICIO",
    searchPlaceholder: "BUSCAR EJERCICIO…",
    cancel: "CANCELAR",
    createOwn: "CREAR PROPIO",
    add: "AGREGAR",
    noResultsPre: "No hay ejercicios para ",
    noneLeft: "No quedan ejercicios para agregar.",
    exerciseNamePlaceholder: "NOMBRE DEL EJERCICIO",
    muscleAria: "Músculo",
    measureAria: "Medida",
    measureReps: "Reps",
    measureHold: "Aguante",
    createAndAdd: "CREAR Y AGREGAR",
    // — agregar ejercicio (vista dedicada) —
    newExercise: "＋ NUEVO EJERCICIO",
    fromLibrary: "＋ DESDE BIBLIOTECA",
    unnamed: "Sin nombre",
    searchTitle: "Buscar",
    tabCreate: "CREAR",
    tabBrowse: "BUSCAR",
    addTo: "AGREGAR A:",
    pattern: "PATRÓN",
    metricRepsLabel: "REPETICIONES",
    metricTimeLabel: "SEGUNDOS",
    optReps: "reps",
    optTime: "tiempo",
    equipConditions: "EQUIPO Y CONDICIONES",
    needsSpace: "NECESITA ESPACIO",
    deskOk: "APTO ESCRITORIO",
    impact: "IMPACTO",
    pickMuscles: "ELEGÍ MÚSCULOS",
    missingPrefix: "FALTA",
    missName: "nombre",
    missPrimary: "1 primario",
    suggested: "SUGERIDO",
    apply: "APLICAR",
    patternWord: "Patrón",
    musclesWord: "músculos",
    musclesPickHint: "tocá un chip o el cuerpo · off → primario → secundario",
  },
  progress: {
    title: "PROGRESO",
    sub: "TU EVOLUCIÓN",
    emptyBefore: "Todavía no registraste series. Marcá ejercicios como",
    emptyDoneWord: "HECHO",
    emptyAfter: "y acá vas a ver tu evolución.",
    weekLabel: "ESTA SEMANA",
    streakLabel: "RACHA",
    activeLabel: "ACTIVOS",
    sets: "SERIES",
    day: "DÍA",
    days: "DÍAS",
    exercises: "EJERCICIOS",
    youreAt: "ESTÁS EN",
    since: "DESDE",
    nextLevel: "SIGUIENTE",
    maxLevel: "NIVEL MÁXIMO",
    ready: "LISTO:",
    last7days: "ÚLTIMOS 7 DÍAS",
  },
  coach: {
    title: "COACH",
    subtitle: "TU ENTRENADOR",
    configureInSettings: "Configurar en Ajustes",
    week: "SEMANA",
    allFits: "TODO ENTRA",
    wontFit: "NO ENTRA",
    ready: "LISTO",
    setsSevenDays: "SERIES · 7D",
    balanced: "EQUILIBRADO",
    diagnostic: "DIAGNÓSTICO",
    conversations: "CONVERSACIONES",
    feasibility: "FACTIBILIDAD",
    progression: "PROGRESIÓN",
    balanceTitle: "BALANCE",
    activeDaysUnit: "días activos",
    history: "HISTORIAL",
    promptFitVolume: "No me entra el volumen, ajustalo para que entre en mi horario",
    promptLevelUpPrefix: "¿Estoy listo para subir de nivel en",
    promptBalance: "Equilibrá los grupos musculares de mi rutina",
    new: "NUEVA",
    noChatsYet: "SIN CHARLAS TODAVÍA",
    resumeInClaudeCode: "Retomar en Claude Code",
    claudeCodeReadOnly: "CLAUDE CODE · SOLO LECTURA",
    emptyOrUnreadable: "SESIÓN VACÍA O ILEGIBLE",
    conversationLivesInClaudeCode: "LA CONVERSACIÓN VIVE EN CLAUDE CODE",
    resumeInClaudeCodeBtn: "RETOMAR EN CLAUDE CODE",
    onboardingTitle: "¿Qué querés lograr?",
    onboardingBody:
      "Te propongo cambios en tu rutina, semana o equipo — y los aprobás antes de aplicar.",
    starters: [
      "Armá mi semana para mi objetivo",
      "Subí mi volumen sin pasarme del horario",
      "Tengo una molestia hoy, adaptá la rutina",
    ],
    thinking: "PENSANDO…",
    inputPlaceholder: "Hablá con el coach…",
    send: "ENVIAR",
    proposedChanges: "CAMBIOS PROPUESTOS",
    apply: "APLICAR",
    discard: "DESCARTAR",
  },
  body: {
    title: "MAPA MUSCULAR",
    coverage: "COBERTURA",
    open: "VER CUERPO",
    front: "FRENTE",
    back: "ESPALDA",
    load: "CARGA",
    sets: "series",
    noExercises: "sin ejercicios que lo trabajen",
    levelNone: "SIN CARGA",
    levelLow: "BAJA",
    levelMid: "MEDIA",
    levelHigh: "ALTA",
    aggregate: "AGREGADO · TODO EL DÍA",
    isolated: "AISLADO",
    allDay: "TODO EL DÍA",
    hoverHint: "PASÁ EL MOUSE PARA AISLAR · CLIC PARA FIJAR",
    primary: "PRIMARIO",
    secondary: "SECUNDARIO",
    untrained: "sin trabajar",
    gapSub: "Ningún ejercicio las cubre hoy",
    add: "AGREGAR",
    coverageDay: "COBERTURA DEL DÍA",
    live: "LIVE",
    musclesNew: "MÚSCULOS · NUEVO",
    spreadHint: "CARGA REPARTIDA EN TODO EL DÍA",
    pickHint: "TOCÁ UN MÚSCULO PARA ASIGNARLO",
    closesLegs: "Cierra el hueco de Piernas",
    stillLegs: "Todavía falta Piernas",
    dayCoverage: "Cobertura del día",
    groupsAtCreate: "GRUPOS AL CREAR",
    legsUncovered: "PIERNAS SIN CUBRIR",
    groupsCovered: "GRUPOS CUBIERTOS",
    groups: "GRUPOS",
    regions: {
      chest: "Pecho",
      back: "Espalda",
      shoulders: "Hombros",
      arms: "Brazos",
      core: "Core",
      legs: "Piernas",
    },
    muscleNames: {
      chest: "Pecho",
      abs: "Abdomen",
      obliques: "Oblicuos",
      biceps: "Bíceps",
      triceps: "Tríceps",
      forearm: "Antebrazo",
      "front-deltoids": "Hombro frontal",
      "back-deltoids": "Hombro posterior",
      trapezius: "Trapecio",
      "upper-back": "Espalda alta",
      "lower-back": "Espalda baja",
      quadriceps: "Cuádriceps",
      hamstring: "Isquios",
      gluteal: "Glúteo",
      calves: "Pantorrillas",
      adductor: "Aductor",
      abductors: "Abductor",
    },
  },
  shell: {
    online: "EN LÍNEA",
    relay: "PAUSA ACTIVA RELAY",
  },
  cal: {
    week: "SEMANA",
    month: "MES",
    months: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
    prev: "Mes anterior",
    next: "Mes siguiente",
    today: "HOY",
    dayPlan: "PLAN DEL DÍA",
    useWeekly: "Usar patrón semanal",
    overrideTag: "EXCEPCIÓN",
    weeklyDefault: "patrón semanal",
    pickDate: "Elegí un día para planearlo",
  },
};

export type Dict = typeof es;

const en: Dict = {
  nav: {
    coach: "COACH",
    today: "TODAY",
    routine: "ROUTINE",
    week: "WEEK",
    equipment: "GEAR",
    progress: "PROGRESS",
    settings: "SETTINGS",
    themeLight: "LIGHT THEME",
    themeDark: "DARK THEME",
  },
  muscle: { pull: "Pull", push: "Push", core: "Core", legs: "Legs" },
  context: { desk: "Desk", space: "Needs space" },
  today: {
    title: "TODAY",
    weekdays: ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"],
    rest: "REST",
    restTitle: "Rest day",
    restSub: "Recover today · back at it tomorrow",
    setsDone: "SETS DONE",
    loadToday: "TODAY'S LOAD",
    theDay: "THE DAY",
    sets: "SETS",
    now: "NOW",
    in: "IN",
    min: "MIN",
    next: "NEXT",
    reps: "REPS",
    minutes: "MINUTES",
    hours: "HOURS",
    done: "DONE",
    snooze: "SNOOZE",
    notNow: "NOT NOW",
    stPending: "PENDING",
    stDone: "DONE",
    stSkipped: "SKIPPED",
    stNow: "NOW",
    stNext: "NEXT",
    stWontFit: "WON'T FIT",
    outOfHours: "OUTSIDE HOURS · THEY'LL SPREAD AGAIN TOMORROW",
    noRoutine: "NO EXERCISES — BUILD YOUR ROUTINE",
  },
  panel: {
    noSets: "No sets",
    next: "NEXT",
    now: "NOW",
    done: "DONE",
    notNow: "NOT NOW",
    min: "MIN",
    h: "H",
    reps: "REPS",
  },
  toast: {
    now: "NOW",
    done: "DONE",
    snooze: "SNOOZE",
    notNow: "NOT NOW",
    reps: "REPS",
  },
  update: {
    label: "UPDATE",
    newVersion: "New version",
    downloading: "DOWNLOADING",
    ready: "READY TO INSTALL",
    failed: "DOWNLOAD FAILED — RETRY",
    install: "UPDATE & RESTART",
    retry: "RETRY",
  },
  settings: {
    title: "SETTINGS",
    sub: "CONFIGURATION",
    appearance: "APPEARANCE",
    theme: "Theme",
    modeLight: "Light",
    modeDark: "Dark",
    modeSystem: "System",
    accent: "Accent",
    language: "LANGUAGE",
    languageLabel: "App language",
    panelSection: "FLOATING PANEL",
    showPanel: "Show panel",
    showPanelHint: "Always-visible mini-window with your next exercise.",
    notifications: "NOTIFICATIONS",
    notifLabel: "microset reminders",
    notifHint: "Pings you when a set is due.",
    snoozeLabel: "Snooze time",
    work: "WORK HOURS",
    start: "Start",
    end: "End",
    lunch: "LUNCH",
    from: "From",
    to: "To",
    minRest: "MINIMUM REST",
    between: "Between sets",
    coach: "COACH",
    provider: "Provider",
    model: "Model",
    modelHint: "Needs ANTHROPIC_API_KEY in the environment.",
    endpoint: "Endpoint",
    endpointHint: "OpenAI-compatible (Ollama / LM Studio).",
    goals: "GOALS",
    goalsPh: "E.g. my first muscle-up, 12 pull-ups, lose fat…",
    diet: "DIET",
    dietPh: "E.g. slight surplus, ~140 g of protein…",
    constraints: "CONSTRAINTS",
    constraintsPh: "E.g. right shoulder niggle, no jumping…",
    demo: "DEMO MODE",
    demoLabel: "Enable demo mode",
    demoHint: "Schedules sets from now, ignoring your hours, to try the app.",
    data: "DATA",
    configFolder: "Config folder",
    configFolderHint: "Your editable JSON: routine, gear, profile, logs.",
    openFolder: "OPEN FOLDER",
    reload: "Reload from files",
    reloadHint: "Re-reads the config from the files instantly.",
    reloadBtn: "RELOAD",
    replan: "Replan today",
    replanHint: "Spreads the sets again from now.",
    replanBtn: "REPLAN",
    resetSettings: "Reset settings",
    resetSettingsHint: "Hours, lunch and rest back to their defaults.",
    resetBtn: "RESET",
    resetAll: "Reset everything",
    resetAllHint: "Wipes routine, gear and logs. Back to factory.",
    resetAllBtn: "RESET ALL",
  },
  week: {
    title: "WEEK",
    sub: "WHAT YOU DO EACH DAY",
    day: "Day",
    place: "Place",
    home: "HOME",
    office: "OFFICE",
  },
  equipment: {
    title: "GEAR",
    sub: "WHAT YOU HAVE AT HOME",
    exercise: "EXERCISE",
    exercises: "EXERCISES",
    inRoutines: "IN ROUTINES",
    custom: "CUSTOM",
    placeholder: "NEW GEAR (E.G. RINGS)",
    add: "ADD",
    removeAria: "Remove gear",
  },
  routine: {
    title: "ROUTINE",
    sub: "BUILD EACH DAY TYPE",
    noDayTypes: "No day types. Reset from Settings or create one.",
    dow: ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"],
    newDayType: "New",
    type: "TYPE",
    dayTypeNameAria: "Day type name",
    unassigned: "UNASSIGNED",
    deleteDayTypeAria: "Delete day type",
    sets: "SETS",
    fitHint: "Trim volume or widen your hours.",
    empty: "EMPTY",
    fits: "FITS ✓",
    fitsCount: "FIT",
    noVolume: "NO VOLUME",
    missing: "MISSING",
    balanced: "BALANCED",
    dayIntensityAria: "Day intensity",
    exercises: "EXERCISES",
    muscles: "MUSCLES · TAP PRIM → SEC → OFF",
    emptyList: "No exercises. Add one with the button below.",
    missingGearAria: "You're missing the gear for this exercise",
    deskTag: "DESK",
    missingGearTag: "MISSING GEAR",
    repsOrDurationAria: "Reps or duration",
    fewerSetsAria: "Fewer sets",
    moreSetsAria: "More sets",
    intensityAria: "Intensity level",
    removeAria: "Remove",
    moveUpAria: "Move up in order",
    moveDownAria: "Move down in order",
    editDayHint: "Edit this day's routine",
    renameHint: "Double-click to rename",
    addExercise: "ADD EXERCISE",
    searchPlaceholder: "SEARCH EXERCISE…",
    cancel: "CANCEL",
    createOwn: "CREATE OWN",
    add: "ADD",
    noResultsPre: "No exercises for ",
    noneLeft: "No exercises left to add.",
    exerciseNamePlaceholder: "EXERCISE NAME",
    muscleAria: "Muscle",
    measureAria: "Measure",
    measureReps: "Reps",
    measureHold: "Hold",
    createAndAdd: "CREATE & ADD",
    // — add exercise (dedicated view) —
    newExercise: "＋ NEW EXERCISE",
    fromLibrary: "＋ FROM LIBRARY",
    unnamed: "Untitled",
    searchTitle: "Search",
    tabCreate: "CREATE",
    tabBrowse: "BROWSE",
    addTo: "ADD TO:",
    pattern: "PATTERN",
    metricRepsLabel: "REPS",
    metricTimeLabel: "SECONDS",
    optReps: "reps",
    optTime: "time",
    equipConditions: "EQUIPMENT & CONDITIONS",
    needsSpace: "NEEDS SPACE",
    deskOk: "DESK-FRIENDLY",
    impact: "IMPACT",
    pickMuscles: "PICK MUSCLES",
    missingPrefix: "NEED",
    missName: "name",
    missPrimary: "1 primary",
    suggested: "SUGGESTED",
    apply: "APPLY",
    patternWord: "Pattern",
    musclesWord: "muscles",
    musclesPickHint: "tap a chip or the body · off → primary → secondary",
  },
  progress: {
    title: "PROGRESS",
    sub: "YOUR EVOLUTION",
    emptyBefore: "You haven't logged any sets yet. Mark exercises as",
    emptyDoneWord: "DONE",
    emptyAfter: "and you'll see your evolution here.",
    weekLabel: "THIS WEEK",
    streakLabel: "STREAK",
    activeLabel: "ACTIVE",
    sets: "SETS",
    day: "DAY",
    days: "DAYS",
    exercises: "EXERCISES",
    youreAt: "YOU'RE AT",
    since: "SINCE",
    nextLevel: "NEXT",
    maxLevel: "MAX LEVEL",
    ready: "READY:",
    last7days: "LAST 7 DAYS",
  },
  coach: {
    title: "COACH",
    subtitle: "YOUR TRAINER",
    configureInSettings: "Configure in Settings",
    week: "WEEK",
    allFits: "ALL FITS",
    wontFit: "WON'T FIT",
    ready: "READY",
    setsSevenDays: "SETS · 7D",
    balanced: "BALANCED",
    diagnostic: "READOUT",
    conversations: "CONVERSATIONS",
    feasibility: "FEASIBILITY",
    progression: "PROGRESSION",
    balanceTitle: "BALANCE",
    activeDaysUnit: "active days",
    history: "HISTORY",
    promptFitVolume: "My volume doesn't fit, adjust it so it fits my schedule",
    promptLevelUpPrefix: "Am I ready to level up on",
    promptBalance: "Balance the muscle groups in my routine",
    new: "NEW",
    noChatsYet: "NO CHATS YET",
    resumeInClaudeCode: "Resume in Claude Code",
    claudeCodeReadOnly: "CLAUDE CODE · READ ONLY",
    emptyOrUnreadable: "EMPTY OR UNREADABLE SESSION",
    conversationLivesInClaudeCode: "THE CONVERSATION LIVES IN CLAUDE CODE",
    resumeInClaudeCodeBtn: "RESUME IN CLAUDE CODE",
    onboardingTitle: "What do you want to achieve?",
    onboardingBody:
      "I'll propose changes to your routine, week, or equipment — and you approve them before they apply.",
    starters: [
      "Build my week for my goal",
      "Increase my volume without overrunning my schedule",
      "I have a niggle today, adapt the routine",
    ],
    thinking: "THINKING…",
    inputPlaceholder: "Talk to the coach…",
    send: "SEND",
    proposedChanges: "PROPOSED CHANGES",
    apply: "APPLY",
    discard: "DISCARD",
  },
  body: {
    title: "MUSCLE MAP",
    coverage: "COVERAGE",
    open: "VIEW BODY",
    front: "FRONT",
    back: "BACK",
    load: "LOAD",
    sets: "sets",
    noExercises: "no exercises work it",
    levelNone: "NO LOAD",
    levelLow: "LOW",
    levelMid: "MED",
    levelHigh: "HIGH",
    aggregate: "AGGREGATE · ALL DAY",
    isolated: "ISOLATED",
    allDay: "ALL DAY",
    hoverHint: "HOVER TO ISOLATE · CLICK TO PIN",
    primary: "PRIMARY",
    secondary: "SECONDARY",
    untrained: "untrained",
    gapSub: "No exercise covers them today",
    add: "ADD",
    coverageDay: "DAY COVERAGE",
    live: "LIVE",
    musclesNew: "MUSCLES · NEW",
    spreadHint: "LOAD SPREAD ACROSS THE DAY",
    pickHint: "TAP A MUSCLE TO ASSIGN IT",
    closesLegs: "Closes the Legs gap",
    stillLegs: "Legs still missing",
    dayCoverage: "Day coverage",
    groupsAtCreate: "GROUPS ON CREATE",
    legsUncovered: "LEGS NOT COVERED",
    groupsCovered: "GROUPS COVERED",
    groups: "GROUPS",
    regions: {
      chest: "Chest",
      back: "Back",
      shoulders: "Shoulders",
      arms: "Arms",
      core: "Core",
      legs: "Legs",
    },
    muscleNames: {
      chest: "Chest",
      abs: "Abs",
      obliques: "Obliques",
      biceps: "Biceps",
      triceps: "Triceps",
      forearm: "Forearm",
      "front-deltoids": "Front delts",
      "back-deltoids": "Rear delts",
      trapezius: "Trapezius",
      "upper-back": "Upper back",
      "lower-back": "Lower back",
      quadriceps: "Quads",
      hamstring: "Hamstrings",
      gluteal: "Glutes",
      calves: "Calves",
      adductor: "Adductor",
      abductors: "Abductors",
    },
  },
  shell: {
    online: "ONLINE",
    relay: "ACTIVE BREAK RELAY",
  },
  cal: {
    week: "WEEK",
    month: "MONTH",
    months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    prev: "Previous month",
    next: "Next month",
    today: "TODAY",
    dayPlan: "DAY PLAN",
    useWeekly: "Use weekly pattern",
    overrideTag: "EXCEPTION",
    weeklyDefault: "weekly pattern",
    pickDate: "Pick a day to plan it",
  },
};

export const STRINGS: Record<Lang, Dict> = { es, en };

/** Default language from the OS/browser locale; Spanish locales → es, else en. */
export function detectLang(): Lang {
  if (typeof navigator !== "undefined" && navigator.language?.toLowerCase().startsWith("es"))
    return "es";
  return "en";
}
