/**
 * App i18n dictionary (EN/ES). Store-free so the Zustand store can import the
 * Lang type + detector without a cycle. `es` is the source of truth; `en` must
 * match its shape (enforced by the `Dict` type).
 */

export type Lang = "es" | "en";

const es = {
  nav: {
    coach: "COACH",
    today: "HOY",
    routine: "RUTINA",
    week: "SEMANA",
    equipment: "EQUIPO",
    progress: "PROGRESO",
    settings: "AJUSTES",
    themeLight: "TEMA CLARO",
    themeDark: "TEMA OSCURO",
  },
  muscle: { pull: "Tirón", push: "Empuje", core: "Core", legs: "Piernas" },
  context: { desk: "De escritorio", space: "Necesita espacio" },
  today: {
    title: "HOY",
    weekdays: ["LUNES", "MARTES", "MIÉRCOLES", "JUEVES", "VIERNES", "SÁBADO", "DOMINGO"],
    rest: "DESCANSO",
    restTitle: "Día de descanso",
    restSub: "Hoy toca recuperar · mañana seguimos",
    setsDone: "SERIES HECHAS",
    theDay: "EL DÍA",
    sets: "SERIES",
    now: "AHORA",
    in: "EN",
    min: "MIN",
    next: "PRÓXIMA",
    reps: "REPS",
    minutes: "MINUTOS",
    hours: "HORAS",
    done: "HECHO",
    snooze: "POSPONER",
    notNow: "AHORA NO",
    stPending: "PENDIENTE",
    stDone: "HECHO",
    stSkipped: "SALTADO",
    stNow: "AHORA",
    stNext: "PRÓXIMA",
    stWontFit: "NO ENTRA",
    outOfHours: "FUERA DE HORARIO · MAÑANA SE REPARTEN DE NUEVO",
    noRoutine: "SIN EJERCICIOS — ARMÁ TU RUTINA",
  },
  panel: {
    noSets: "Sin series",
    next: "PRÓXIMA",
    now: "AHORA",
    done: "HECHO",
    notNow: "AHORA NO",
    min: "MIN",
    h: "H",
    reps: "REPS",
  },
  toast: {
    now: "AHORA",
    done: "HECHO",
    snooze: "POSPONER",
    notNow: "AHORA NO",
    reps: "REPS",
  },
  update: {
    label: "ACTUALIZACIÓN",
    newVersion: "Nueva versión",
    downloading: "DESCARGANDO",
    ready: "LISTA PARA INSTALAR",
    failed: "FALLÓ LA DESCARGA — REINTENTÁ",
    install: "ACTUALIZAR Y REINICIAR",
    retry: "REINTENTAR",
  },
  settings: {
    title: "AJUSTES",
    sub: "CONFIGURACIÓN",
    appearance: "APARIENCIA",
    theme: "Tema",
    modeLight: "Claro",
    modeDark: "Oscuro",
    modeSystem: "Sistema",
    accent: "Acento",
    language: "IDIOMA",
    languageLabel: "Idioma de la app",
    panelSection: "PANEL FLOTANTE",
    showPanel: "Mostrar panel",
    showPanelHint: "Mini-ventana siempre visible con el próximo ejercicio.",
    notifications: "NOTIFICACIONES",
    notifLabel: "Avisos de microset",
    notifHint: "Te avisa cuando toca una serie.",
    snoozeLabel: "Tiempo de posponer",
    work: "HORARIO LABORAL",
    start: "Inicio",
    end: "Fin",
    lunch: "ALMUERZO",
    from: "Desde",
    to: "Hasta",
    minRest: "DESCANSO MÍNIMO",
    between: "Entre series",
    coach: "COACH",
    provider: "Proveedor",
    model: "Modelo",
    modelHint: "Necesita ANTHROPIC_API_KEY en el entorno.",
    endpoint: "Endpoint",
    endpointHint: "OpenAI-compatible (Ollama / LM Studio).",
    goals: "OBJETIVOS",
    goalsPh: "Ej: mi primer muscle-up, 12 dominadas, bajar grasa…",
    diet: "DIETA",
    dietPh: "Ej: superávit leve, ~140 g de proteína…",
    constraints: "RESTRICCIONES",
    constraintsPh: "Ej: molestia en hombro derecho, sin saltos…",
    demo: "MODO DEMO",
    demoLabel: "Activar modo demo",
    demoHint: "Agenda series desde ahora, ignorando tu horario, para probar la app.",
    data: "DATOS",
    configFolder: "Carpeta de config",
    configFolderHint: "Tus JSON editables: rutina, equipo, perfil, logs.",
    openFolder: "ABRIR CARPETA",
    reload: "Recargar desde archivos",
    reloadHint: "Re-lee la config de los archivos al instante.",
    reloadBtn: "RECARGAR",
    replan: "Replanificar hoy",
    replanHint: "Vuelve a repartir las series desde ahora.",
    replanBtn: "REPLANIFICAR",
    resetSettings: "Restablecer ajustes",
    resetSettingsHint: "Horario, almuerzo y descanso a sus valores iniciales.",
    resetBtn: "RESTABLECER",
    resetAll: "Restablecer todo",
    resetAllHint: "Borra rutina, equipo y registros. Vuelve de fábrica.",
    resetAllBtn: "RESTABLECER TODO",
  },
};

export type Dict = typeof es;

const en: Dict = {
  nav: {
    coach: "COACH",
    today: "TODAY",
    routine: "ROUTINE",
    week: "WEEK",
    equipment: "GEAR",
    progress: "PROGRESS",
    settings: "SETTINGS",
    themeLight: "LIGHT THEME",
    themeDark: "DARK THEME",
  },
  muscle: { pull: "Pull", push: "Push", core: "Core", legs: "Legs" },
  context: { desk: "Desk", space: "Needs space" },
  today: {
    title: "TODAY",
    weekdays: ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"],
    rest: "REST",
    restTitle: "Rest day",
    restSub: "Recover today · back at it tomorrow",
    setsDone: "SETS DONE",
    theDay: "THE DAY",
    sets: "SETS",
    now: "NOW",
    in: "IN",
    min: "MIN",
    next: "NEXT",
    reps: "REPS",
    minutes: "MINUTES",
    hours: "HOURS",
    done: "DONE",
    snooze: "SNOOZE",
    notNow: "NOT NOW",
    stPending: "PENDING",
    stDone: "DONE",
    stSkipped: "SKIPPED",
    stNow: "NOW",
    stNext: "NEXT",
    stWontFit: "WON'T FIT",
    outOfHours: "OUTSIDE HOURS · THEY'LL SPREAD AGAIN TOMORROW",
    noRoutine: "NO EXERCISES — BUILD YOUR ROUTINE",
  },
  panel: {
    noSets: "No sets",
    next: "NEXT",
    now: "NOW",
    done: "DONE",
    notNow: "NOT NOW",
    min: "MIN",
    h: "H",
    reps: "REPS",
  },
  toast: {
    now: "NOW",
    done: "DONE",
    snooze: "SNOOZE",
    notNow: "NOT NOW",
    reps: "REPS",
  },
  update: {
    label: "UPDATE",
    newVersion: "New version",
    downloading: "DOWNLOADING",
    ready: "READY TO INSTALL",
    failed: "DOWNLOAD FAILED — RETRY",
    install: "UPDATE & RESTART",
    retry: "RETRY",
  },
  settings: {
    title: "SETTINGS",
    sub: "CONFIGURATION",
    appearance: "APPEARANCE",
    theme: "Theme",
    modeLight: "Light",
    modeDark: "Dark",
    modeSystem: "System",
    accent: "Accent",
    language: "LANGUAGE",
    languageLabel: "App language",
    panelSection: "FLOATING PANEL",
    showPanel: "Show panel",
    showPanelHint: "Always-visible mini-window with your next exercise.",
    notifications: "NOTIFICATIONS",
    notifLabel: "microset reminders",
    notifHint: "Pings you when a set is due.",
    snoozeLabel: "Snooze time",
    work: "WORK HOURS",
    start: "Start",
    end: "End",
    lunch: "LUNCH",
    from: "From",
    to: "To",
    minRest: "MINIMUM REST",
    between: "Between sets",
    coach: "COACH",
    provider: "Provider",
    model: "Model",
    modelHint: "Needs ANTHROPIC_API_KEY in the environment.",
    endpoint: "Endpoint",
    endpointHint: "OpenAI-compatible (Ollama / LM Studio).",
    goals: "GOALS",
    goalsPh: "E.g. my first muscle-up, 12 pull-ups, lose fat…",
    diet: "DIET",
    dietPh: "E.g. slight surplus, ~140 g of protein…",
    constraints: "CONSTRAINTS",
    constraintsPh: "E.g. right shoulder niggle, no jumping…",
    demo: "DEMO MODE",
    demoLabel: "Enable demo mode",
    demoHint: "Schedules sets from now, ignoring your hours, to try the app.",
    data: "DATA",
    configFolder: "Config folder",
    configFolderHint: "Your editable JSON: routine, gear, profile, logs.",
    openFolder: "OPEN FOLDER",
    reload: "Reload from files",
    reloadHint: "Re-reads the config from the files instantly.",
    reloadBtn: "RELOAD",
    replan: "Replan today",
    replanHint: "Spreads the sets again from now.",
    replanBtn: "REPLAN",
    resetSettings: "Reset settings",
    resetSettingsHint: "Hours, lunch and rest back to their defaults.",
    resetBtn: "RESET",
    resetAll: "Reset everything",
    resetAllHint: "Wipes routine, gear and logs. Back to factory.",
    resetAllBtn: "RESET ALL",
  },
};

export const STRINGS: Record<Lang, Dict> = { es, en };

/** Default language from the OS/browser locale; Spanish locales → es, else en. */
export function detectLang(): Lang {
  if (typeof navigator !== "undefined" && navigator.language?.toLowerCase().startsWith("es"))
    return "es";
  return "en";
}
